project:
  type: website
  output-dir: docs


website:
  title: "ScriptNdebug"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mnahmad
      - icon: twitter
        href: https://x.com/mnabiahmad
      - icon: Linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/muhammad-nabi-ahmad-2459a85

format:
  html:
    theme: cosmo
    css: styles.css



